server:
  port: 8888

spring:
  application:
    name: CLOUD-CONFIG

  cloud:
    config:
      server:
        git:
          uri: https://github.com/s2taaa/cloud-config
          default-label: main
        bootstrap: false