server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/s2taaa/cloudconfigserver
          default-label: main
        bootstrap: false