resilience4j:
  retry:
    instances:
      # Retry object used in RetryingService.basicExample()
      basic:
        maxRetryAttempts: 3
        waitDuration: 10s
ratelimiter:
  instances:
    # RateLimiter object used in RateLimitingService.basicExample()
    basicExample:
      limitForPeriod: 1
      limitRefreshPeriod: 1s
      timeoutDuration: 1s
