resilience4j:
  retry:
    instances:
      # Retry object used in RetryingService.basicExample()
      basic:
        maxRetryAttempts: 3
        waitDuration: 10s
  ratelimiter:
    instances:
    # RateLimiter object used in RateLimitingService.basicExample()
      basicExample:
        limitForPeriod: 2
        limitRefreshPeriod: 5s
        timeoutDuration: 2s

spring:
  application:
    name: USER-SERVICE


eureka:
  client:
    register-with-eureka:
      value: true
    fetch-registry:
      value: true;
    service-url:
      defaultZone: http://ec2-54-169-171-22.ap-southeast-1.compute.amazonaws.com:8761/eureka
    instance:
      hostname: localhost